name: cache_systems
description: A new Flutter package project.
version: 0.0.1
homepage: https://www.merterim.dev

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hive_flutter: ^1.1.0
  hive: ^2.2.3
  dio: ^5.3.3
  path_provider: ^2.1.1
  cross_file: ^0.3.3+6
  universal_io: ^2.2.2
  mime: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.4
