name: cache_systems
description: A Flutter package for caching various file types (images, videos, text, etc.) on a device, including those from the internet.
version: 0.0.5
homepage: https://github.com/wirdes/cache_systems


environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  hive_flutter: ^1.1.0
  hive: ^2.2.3
  dio: ^5.3.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.0.4
